### ISSUE TITLE
匯入台華

### ISSUE THREAD

**Issue by sih4sing5hong5** [Taiwanese-Corpus/hue7jip8#13]
1. 加試驗，加新的`試驗`資料夾
1. 加指令
2. 共[csv](https://github.com/Taiwanese-Corpus/Tinn-liong-ui_2000_taihoa-dictionary/tree/master/%E6%95%99%E8%82%B2%E9%83%A8%E5%BB%BA%E8%AD%B0%E7%94%A8%E5%AD%97)掠落來
3. csv解析會當參考[itaigi](https://github.com/g0v/itaigi/blob/master/server-side/%E5%8C%AF%E5%85%A5%E5%8F%B0%E8%8F%AF.py)的程式
4. 因為台華無音檔，所以愛用
```
外語表.加資料(外語內容)
外語.翻母語(文本內容)`
```
匯入會當參考[教典匯入](https://github.com/sih4sing5hong5/hue7jip8/blob/master/%E5%8C%AF%E5%85%A5%E5%88%B0%E8%87%BA%E7%81%A3%E8%A8%80%E8%AA%9E%E8%B3%87%E6%96%99%E5%BA%AB/management/commands/%E6%95%99%E5%85%B8%E9%9F%B3%E6%AA%942%E5%8C%AF%E5%85%A5.py#L56-L86)，

### 範例
csv的資料

ID | 台語羅馬字 | 台語羅馬字2 | 台語漢字 | 華語對譯 | 英文 | freq | pos_h
-- | -- | -- | -- | -- | -- | -- | --
12 | a-bo2 | a-bu2 | 阿母 | ;母親;媽媽; | mother | 1884 | Na

愛產生佇資料庫的資料

外語ID | 外語腔口 | 外語資料
-- | -- | -- 
1 | 華語 | 母親
2 | 華語 | 媽媽
3 | 英語 | mother

逐个外語攏有2个獨立的文本

文本ID | 語言腔口 | 文本資料 | 音標資料
-- | -- | -- | -- 
1 | 臺語 | 阿母 | a-bo2 
2 | 臺語 | 阿母 | a-bu2
3 | 臺語 | 阿母 | a-bo2 
4 | 臺語 | 阿母 | a-bu2
5 | 臺語 | 阿母 | a-bo2 
6 | 臺語 | 阿母 | a-bu2

教羅要轉臺羅

**Comment by a8568730** [comment]
[台灣語言資料庫的外語表文件](http://sih4sing5hong5.github.io/tai5-uan5_gian5-gi2_tsu1-liau7-khoo3/%E8%B3%87%E6%96%99%E7%B5%90%E6%A7%8B.html)
